### ISSUE TITLE
Policy on feedback to the NomCom is too restrictive

### ISSUE THREAD

**Issue by JayDaley** [ietf-llc/community-engagement-policy-consultation#1]
The original feedback was:

> And then I think about interesting cases that the nomcom needs to know about.  Creating an example that is to the best of my knowledge completely fictitious, if a candidate for IETF Chair had a history of difficult interactions with either the RPC or the IETF Executive Director, it would seem that the nomcom should know about that.  And be able to get the information from the direct participants.  This policy would prohibit such direct communication.
> (Yes, the nomcom might pick that person anyway.  The reasons for choices are manifold and complex.  I am concerned merely that the nomcom be able to get relevant information.)

And then further feedback was provided in response to being asked if the formal LLC board representative is a sufficient mechanism:

> 1) If the interaction is with the RPC, it is unlikley that the LLC Board liaison will even know about the issues.  Even if the interaction is with you, I would be unsurprised if you had been discreet enough not to raise the issues with the LLC board unless the problem was actually interfering with your work.  But that does not mean that it is not useful information for the nomcom.
> 1') Even worse would be the case where the person with interaction difficulties was a sitting LLC Board member.  The liaison would find it almost impossible to relay the issues.  (Yes, there is a problem that the issue will come to the attention of the LLC Board Liaison.  That is a different topic.  I believe folks are aware that that can serve as a damper on feedback about sitting IAB or IESG members.  That is a topic for a different list.  And a very messy topic for which I do not know any remedies.)
> 
> 2) One of the complications I have observed for the nomcom in various circumstances is that it is very hard to act on or even evaluate second hand information.  Too much gets lost, and there is too much inherent uncertainty about the underlying details.

**Comment by samuelweiler** [comment]
Once again, I concur.  The NomCom gets biased feedback all the time and we trust them to sort it out.  This hypothetical is no different.  Just let NomCom take the feedback and run with it.
