### ISSUE TITLE
What is a Covered Role?

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/community-engagement-policy-consultation#12]
Covered Role is a term in https://github.com/ietf-llc/community-engagement-policy-consultation/blob/latest-updates-from-consultation/DRAFT%20Additional%20section%20for%20Code%20of%20Conduct%20Policy.md. Is that defined somewhere? If not it should be defined in that new text.

**Comment by JayDaley** [comment]
If the amendment is accepted then I'll add that to the policy in the definitions section as "the role(s) that makes someone a Covered Individual".
