### ISSUE TITLE
Policy on RPC engagement in development of RFCs is too restrictive

### ISSUE THREAD

**Issue by JayDaley** [ietf-llc/community-engagement-policy-consultation#2]
From feedback:

> The restrictions on the RPC seem to go too far.  While it is true that most of the people who work for the RPC are not IETF participants, some of them are.  And they should be permitted to do so.

**Comment by samuelweiler** [comment]
Concur.  Same logic as https://github.com/ietf-llc/community-engagement-policy-consultation/issues/4#issuecomment-707110008

**Comment by jlivingood** [comment]
What specifically is the proposed change? "Too restrictive" is vague here. Please provide a suggested specific change for discussion.

**Comment by jlivingood** [comment]
noting also: Open Q seems from the list to be whether something COI-related has a place in an engagement policy.

**Comment by jlivingood** [comment]
Looks like Jay's revisions (in process) will address this point of community feedback.
