### ISSUE TITLE
Staff, secretariat and RPC who are subject matter experts should be allowed to contribute to RFC work

### ISSUE THREAD

**Issue by JayDaley** [ietf-llc/community-engagement-policy-consultation#4]
Feedback was:

> I don't see how this will work if a staff member happens to be a subject matter expert and the IETF needs that expertise. I don't see the conflict of interest that we might be trying to avoid in that case. Suppose that an employee happens to be an expert in congestion control. Who is harmed, or who is in conflict, if they contribute to a discussion of congestion control in the QUIC WG? On the contrary, if they *don't* contribute, the IETF is harmed because it doesn't get the benefit of their expertise.
> 
> I can certainly see that they shouldn't do this during working hours, because they are paid to do something else then, but there are another 128 hours a week available for them to contribute to the IETF as private individuals.
> 
> It seems to me that the policy should be different. Something like:
> 
> "Staff, Secretariat and RPC are not expected to have any engagement regarding the content of technical standards as part of their job, except as required in their defined administrative roles. For Secretariat and RPC this may occasionally include contributing to or authoring RFCs related to their area of work. However, in accordance with IETF principles, they may contribute freely to IETF technical discussions as private individuals in their own time."
> 
> There might well be conflict of interest if a staff member contributes to the discussion of a process RFC that concerns their own work, so there naturally need to be some rules about that, as set out in the draft policy.

**Comment by samuelweiler** [comment]
I can easily imagine a existing IETF participant taking one of these roles, perhaps just on an interim basis, and this rule needs to be relaxed.  e.g. I wouldn't want to force an active contributor to stop all contributions in order to take on the role of Interim exec director - we don't want to lose the option to have an otherwise-well-qualified individual step into those exec director shoes.
