### ISSUE TITLE
Allow contractors to serve on NomCom

### ISSUE THREAD

**Issue by samuelweiler** [ietf-llc/community-engagement-policy-consultation#5]
Having served on NomComs alongside IETF tools contributors, I would not want to see someone excluded just because they had a contract of some sort.

I recall a conflict of interest policy that opened by acknowledging that "persons of substance" (or somesuch) with the sorts of board expertise desired for the job would come with conflicts.  As active IETF participants, the NomCom members themselves each come with a pile of conflicts.  As does everyone providing feedback.  NomComs are aware of that and sort it out, year after year.

The proposed restrictions are excessive.

**Comment by jlivingood** [comment]
"As active IETF participants, the NomCom members themselves each come with a pile of conflicts."

Be that as it may, it seems rather different & problematic to have someone who is for example paid by the IETF LLC as a contractor or employee providing feedback on potential IETF LLC board members. It seems more prudent to avoid this as it is not a perceived conflict of interest but an actual conflict of interest. As the number of NomCom volunteers always exceeds the number of NomCom slots needed, it seems this should not have a material affect on the pool of eligible NomCom volunteers.

**Comment by jlivingood** [comment]
Open Q seems from the list to be whether something COI-related has a place in an engagement policy.

**Comment by jlivingood** [comment]
Looks like Jay's revisions (in process) will address this point of community feedback.
